### ISSUE TITLE
Database connection error

### ISSUE THREAD

**Issue by Menphis88** [KaiKikuchi/Sync#1]
Hey kai, been using Sync on my old server, and it worked like a charm, but now that im setting up a new one, i cant seem to get the plugin to connect, thoug i am pretty sure i am using the proper syntax.

Sync config:
http://pastebin.com/R2XKa1H7
Server log:
http://pastebin.com/bHajURWE

I have tried making new databases, with and without passwords, but still no luck.

And thank you VERY much for all your awesome plugins, you are so talented and the plugins are simply fantastic. So keep up the good work.
//Mark

**Comment by KaiKikuchi** [comment]
Hello, it looks like there's some issue with your MySQL database, or your MySQL server address, username and/or password are wrong.

Do you use any other plugin that uses your MySQL server?
